### ISSUE TITLE
✨ MAJOR TRACKING ISSUE ✨ 

### ISSUE THREAD

**Issue by mishmanners** [mishmanners/mish-friendly-food#6]
**Phase 1**:
- [ ] Decide on the best database format
- [ ] Collect and scrape known databases for food types
- [ ] Call for translation in multiple languages

**Phase 2:**
- [ ] Build the translation capability
- [ ] Build out the basic website
- [ ] Database calling

**Phase 3:**
- [ ] Creative images for the cards
- [ ] Exporting the cards
- [ ] Exporting as text file

**Comment by mishmanners** [comment]
We are getting there! Good work team :heart:
